[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydal-rqlite"
description = "Custom pyDAL adapter for rqlite (distributed SQLite)"
readme = "README.md"
requires-python = ">=3.10"
license-expression = "MIT"
authors = [
    {name = "Robin van der Noord", email = "robin.vdn@educationwarehouse.nl"}
]
urls = { "Homepage" = "https://github.com/educationwarehouse/pydal-adapter-rqlite" }

dependencies = [
    "pydal",
    "pyrqlite",
]
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["pydal_rqlite"]

[tool.vommit]
allow_breaking_bang = true
allow_breaking_footer = true
prerelease_token = "beta"
confirm = true
ignore = ["hatchling-backend"]

[tool.vommit.git]
enabled = true
origin = "origin"
branch = "master"
on_wrong_branch = "error"
tag_format = "v{version}"
commit_format = "{version}"

[tool.vommit.changelog]
enabled = true
file = "CHANGELOG.md"
include_prereleases = false
placeholder = "<!--next-version-placeholder-->"
placeholder_regex = "<auto>"
entry_title_format = "## v{version} ({date:%Y-%m-%d})"

[tool.vommit.changelog.levels]
feat = "Feature{s}"
fix = "Fix{es}"
break = "Breaking Change{s}"
docs = "Documentation"
perf = "Performance"

[tool.vommit.pypi]
enabled = true
use_keyring = true

[tool.vommit.commands]
clean = "rm -rf ./dist"
build = "uv build"
publish = "uv publish"
post_publish = ""

[tool.vommit.version_bump_map]
break = "major"
feat = "minor"
fix = "patch"
perf = "patch"
